### ISSUE TITLE
Snippets are showing up in .js files

### ISSUE THREAD

**Issue by mattwaler** [fivethree-team/vscode-svelte-snippets#6]
Svelte snippets are showing up when working on React projects (working with `.js` files). Is this by design?

![Screen Shot 2019-12-17 at 9 09 31 AM](https://user-images.githubusercontent.com/32300026/71002311-fd0a5d00-20ac-11ea-8fa5-52692e28695b.png)

**Comment by mlbiche** [comment]
Yes, it is by design, as you CSS Svelte snippet is showing up in .css file. The _package.json_ file is configured as follow :

```
        "snippets": [
            {
                "language": "svelte",
                "path": "./snippets/svelte.json"
            },
            {
                "language": "javascript",
                "path": "./snippets/svelte-script.json"
            },
            {
                "language": "css",
                "path": "./snippets/svelte-style.json"
            }
        ]
```

I am not really sure that there is a better way to do but as a temporary fix, you can disable the extension and then enable it only in workspaces in which you are working with Svelte framework.
